# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [1]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [2]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df =  pd.read_csv(
    Path("C:/Users/PC2/Downloads/challange_13/Starter_Code/Resources/applicants_data.csv")
)

In [3]:
# Review the DataFrame
# YOUR CODE HERE
applicant_data_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
# Review the data types associated with the columns
# YOUR CODE HERE
applicant_data_df.dtypes

EIN                        int64
NAME                      object
APPLICATION_TYPE          object
AFFILIATION               object
CLASSIFICATION            object
USE_CASE                  object
ORGANIZATION              object
STATUS                     int64
INCOME_AMT                object
SPECIAL_CONSIDERATIONS    object
ASK_AMT                    int64
IS_SUCCESSFUL              int64
dtype: object

In [5]:
# Remove white spaces
applicant_data_df.columns = applicant_data_df.columns.str.strip()
applicant_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   EIN                     34299 non-null  int64
 1   NAME                    34299 non-null  object
 2   APPLICATION_TYPE        34299 non-null  object
 3   AFFILIATION             34299 non-null  object
 4   CLASSIFICATION          34299 non-null  object
 5   USE_CASE                34299 non-null  object
 6   ORGANIZATION            34299 non-null  object
 7   STATUS                  34299 non-null  int64
 8   INCOME_AMT              34299 non-null  object
 9   SPECIAL_CONSIDERATIONS  34299 non-null  object
 10  ASK_AMT                 34299 non-null  int64
 11  IS_SUCCESSFUL           34299 non-null  int64
dtypes: int64(4), object(8)
memory usage: 3.1+ MB

In [6]:
applicant_data_df.columns

Index(['EIN', 'NAME', 'APPLICATION_TYPE', 'AFFILIATION', 'CLASSIFICATION',
       'USE_CASE', 'ORGANIZATION', 'STATUS', 'INCOME_AMT',
       'SPECIAL_CONSIDERATIONS', 'ASK_AMT', 'IS_SUCCESSFUL'],
      dtype='object')

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [7]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(columns=["EIN","NAME"])

# Review the DataFrame
# YOUR CODE HERE
applicant_data_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [8]:
# Create a list of categorical variables 
categorical_variables = ["AFFILIATION","CLASSIFICATION", "USE_CASE", "ORGANIZATION", "SPECIAL_CONSIDERATIONS", "IS_SUCCESSFUL"]

# Display the categorical variables list
# YOUR CODE HERE
categorical_variables

['AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'SPECIAL_CONSIDERATIONS',
 'IS_SUCCESSFUL']

In [9]:
# Create a OneHotEncoder instance
enc = enc = OneHotEncoder(sparse_output=False)

In [10]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

In [11]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(
    encoded_data,
    columns = enc.get_feature_names_out(categorical_variables)
)
# Review the DataFrame
# YOUR CODE HERE
encoded_df.head()

,AFFILIATION_CompanySponsored,AFFILIATION_Family/Parent,AFFILIATION_Independent,AFFILIATION_National,AFFILIATION_Other,AFFILIATION_Regional,CLASSIFICATION_C0,CLASSIFICATION_C1000,CLASSIFICATION_C1200,CLASSIFICATION_C1230,...,USE_CASE_Preservation,USE_CASE_ProductDev,ORGANIZATION_Association,ORGANIZATION_Co-operative,ORGANIZATION_Corporation,ORGANIZATION_Trust,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,IS_SUCCESSFUL_0,IS_SUCCESSFUL_1
0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
4,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [12]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
numerical_df = applicant_data_df[["STATUS", "INCOME_AMT", "ASK_AMT"]]	

# Review the Dataframe
# YOUR CODE HERE
numerical_df.head()

   STATUS     INCOME_AMT  ASK_AMT
0       1              0     5000
1       1         1-9999   108590
2       1              0     5000
3       1    10000-24999     6692
4       1  100000-499999   142590

In [13]:
pp_df = pd.concat([numerical_df,encoded_df], axis = 1)
pp_df

,STATUS,INCOME_AMT,ASK_AMT,AFFILIATION_CompanySponsored,AFFILIATION_Family/Parent,AFFILIATION_Independent,AFFILIATION_National,AFFILIATION_Other,AFFILIATION_Regional,CLASSIFICATION_C0,...,USE_CASE_Preservation,USE_CASE_ProductDev,ORGANIZATION_Association,ORGANIZATION_Co-operative,ORGANIZATION_Corporation,ORGANIZATION_Trust,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y,IS_SUCCESSFUL_0,IS_SUCCESSFUL_1
0,1,0,5000,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,1,1-9999,108590,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0
2,1,0,5000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,1,10000-24999,6692,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
4,1,100000-499999,142590,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,0,5000,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
34295,1,0,5000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
34296,1,0,5000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
34297,1,0,5000,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
34298,1,1M-5M,36500179,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [14]:
# Define the target set y using the IS_SUCCESSFUL column
y = pp_df["IS_SUCCESSFUL_1"]

# Display a sample of y
# YOUR CODE HERE
y.head()

0    1.0
1    1.0
2    0.0
3    1.0
4    1.0
Name: IS_SUCCESSFUL_1, dtype: float64

In [15]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = pp_df.drop(columns=["IS_SUCCESSFUL_1", "IS_SUCCESSFUL_0"])

# Review the features DataFrame
# YOUR CODE HERE
X

,STATUS,INCOME_AMT,ASK_AMT,AFFILIATION_CompanySponsored,AFFILIATION_Family/Parent,AFFILIATION_Independent,AFFILIATION_National,AFFILIATION_Other,AFFILIATION_Regional,CLASSIFICATION_C0,...,USE_CASE_Heathcare,USE_CASE_Other,USE_CASE_Preservation,USE_CASE_ProductDev,ORGANIZATION_Association,ORGANIZATION_Co-operative,ORGANIZATION_Corporation,ORGANIZATION_Trust,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,0,5000,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
1,1,1-9999,108590,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2,1,0,5000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
3,1,10000-24999,6692,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
4,1,100000-499999,142590,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,0,5000,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
34295,1,0,5000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
34296,1,0,5000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
34297,1,0,5000,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0
34298,1,1M-5M,36500179,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0

### Step 6: Split the features and target sets into training and testing datasets.

In [16]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [17]:
X_train = X_train.apply(pd.to_numeric, errors='coerce')
X_train = X_train.fillna(0)
X_test = X_test.apply(pd.to_numeric, errors='coerce')
X_test = X_test.fillna(0)

In [18]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [19]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

91

In [20]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [21]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  (number_input_features + 1) // 2 

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

46

In [22]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  (hidden_nodes_layer1 + 1) // 2

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

23

In [23]:
# Create the Sequential model instance
nn = Sequential()

In [24]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

In [25]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))

In [26]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=1, activation="sigmoid"))

In [27]:
# Display the Sequential model summary
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 46)                4232

 dense_1 (Dense)             (None, 23)                1081

 dense_2 (Dense)             (None, 1)                 24

=================================================================
Total params: 5337 (20.85 KB)
Trainable params: 5337 (20.85 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [28]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [29]:
# Fit the model using 50 epochs and the training data
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 7s 5ms/step - loss: 0.6070 - accuracy: 0.6894
Epoch 2/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5889 - accuracy: 0.6986
Epoch 3/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5860 - accuracy: 0.6985
Epoch 4/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5847 - accuracy: 0.7004
Epoch 5/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5833 - accuracy: 0.7007
Epoch 6/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5834 - accuracy: 0.6995
Epoch 7/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5829 - accuracy: 0.7009
Epoch 8/50
804/804 [==============================] - 4s 6ms/step - loss: 0.5827 - accuracy: 0.7017
Epoch 9/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5823 - accuracy: 0.7013
Epoch 10/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5823 - accuracy: 0.7029
Epoch 11/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5816 - accuracy: 0.7003
Epoch 12/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5817 - accuracy: 0.7025
Epoch 13/50
804/804 [==============================] - 3s 4ms/step - loss: 0.5811 - accuracy: 0.7037
Epoch 14/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5807 - accuracy: 0.7018
Epoch 15/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5811 - accuracy: 0.7022
Epoch 16/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5797 - accuracy: 0.7030
Epoch 17/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5804 - accuracy: 0.7043
Epoch 18/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5802 - accuracy: 0.7031
Epoch 19/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5795 - accuracy: 0.7038
Epoch 20/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5793 - accuracy: 0.7035
Epoch 21/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5799 - accuracy: 0.7027
Epoch 22/50
804/804 [==============================] - 4s 4ms/step - loss: 0.5793 - accuracy: 0.7050
Epoch 23/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5792 - accuracy: 0.7042
Epoch 24/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5792 - accuracy: 0.7043
Epoch 25/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5789 - accuracy: 0.7047
Epoch 26/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5789 - accuracy: 0.7040
Epoch 27/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5789 - accuracy: 0.7037
Epoch 28/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5782 - accuracy: 0.7025
Epoch 29/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5783 - accuracy: 0.7044
Epoch 30/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5782 - accuracy: 0.7038
Epoch 31/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5778 - accuracy: 0.7043
Epoch 32/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5777 - accuracy: 0.7047
Epoch 33/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5774 - accuracy: 0.7045
Epoch 34/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5772 - accuracy: 0.7056
Epoch 35/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5775 - accuracy: 0.7055
Epoch 36/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5771 - accuracy: 0.7050
Epoch 37/50
804/804 [==============================] - 4s 6ms/step - loss: 0.5775 - accuracy: 0.7050
Epoch 38/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5776 - accuracy: 0.7045
Epoch 39/50
804/804 [==============================] - 4s 4ms/step - loss: 0.5769 - accuracy: 0.7064
Epoch 40/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5769 - accuracy: 0.7046
Epoch 41/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5770 - accuracy: 0.7049
Epoch 42/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5763 - accuracy: 0.7065
Epoch 43/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5766 - accuracy: 0.7072
Epoch 44/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5766 - accuracy: 0.7055
Epoch 45/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5763 - accuracy: 0.7055
Epoch 46/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5763 - accuracy: 0.7051
Epoch 47/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5766 - accuracy: 0.7050
Epoch 48/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5768 - accuracy: 0.7065
Epoch 49/50
804/804 [==============================] - 4s 5ms/step - loss: 0.5760 - accuracy: 0.7059
Epoch 50/50
804/804 [==============================] - 5s 6ms/step - loss: 0.5758 - accuracy: 0.7063

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [30]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5810 - accuracy: 0.7082 - 1s/epoch - 5ms/step
Loss: 0.5809672474861145, Accuracy: 0.7082215547561646

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [32]:
# Set the model's file path
file_path = Path("Resources/AlphabetSoup.h5")

# Export your model to an HDF5 file
nn.save(file_path)

C:\Users\PC2\anaconda3\Lib\site-packages\keras\src\engine\training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [33]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

91

In [34]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [35]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 =  (number_input_features + 1) // 2 

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

46

In [36]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [37]:
# First hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Output layer
nn_A1.add(Dense(units=1, activation="linear"))

# Check the structure of the model
nn_A1.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 46)                4232

 dense_4 (Dense)             (None, 1)                 47

=================================================================
Total params: 4279 (16.71 KB)
Trainable params: 4279 (16.71 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [38]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [39]:
# Fit the model using 100 epochs and the training data
# Adding another 50 epochs to improve the nn.
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 6s 5ms/step - loss: 2.4899 - accuracy: 0.5957
Epoch 2/100
804/804 [==============================] - 4s 5ms/step - loss: 1.4816 - accuracy: 0.6605
Epoch 3/100
804/804 [==============================] - 4s 5ms/step - loss: 1.4561 - accuracy: 0.6616
Epoch 4/100
804/804 [==============================] - 5s 6ms/step - loss: 1.2671 - accuracy: 0.6688
Epoch 5/100
804/804 [==============================] - 4s 5ms/step - loss: 1.0174 - accuracy: 0.6873
Epoch 6/100
804/804 [==============================] - 5s 6ms/step - loss: 1.0801 - accuracy: 0.6808
Epoch 7/100
804/804 [==============================] - 3s 4ms/step - loss: 1.1366 - accuracy: 0.6848
Epoch 8/100
804/804 [==============================] - 2s 3ms/step - loss: 1.3081 - accuracy: 0.6642
Epoch 9/100
804/804 [==============================] - 3s 4ms/step - loss: 1.5739 - accuracy: 0.6500
Epoch 10/100
804/804 [==============================] - 4s 4ms/step - loss: 1.5652 - accuracy: 0.6517
Epoch 11/100
804/804 [==============================] - 4s 5ms/step - loss: 1.5618 - accuracy: 0.6554
Epoch 12/100
804/804 [==============================] - 4s 6ms/step - loss: 1.5576 - accuracy: 0.6575
Epoch 13/100
804/804 [==============================] - 4s 5ms/step - loss: 1.4780 - accuracy: 0.6620
Epoch 14/100
804/804 [==============================] - 4s 5ms/step - loss: 1.3581 - accuracy: 0.6599
Epoch 15/100
804/804 [==============================] - 3s 4ms/step - loss: 1.2647 - accuracy: 0.6706
Epoch 16/100
804/804 [==============================] - 4s 5ms/step - loss: 1.1493 - accuracy: 0.6782
Epoch 17/100
804/804 [==============================] - 4s 5ms/step - loss: 0.9809 - accuracy: 0.6901
Epoch 18/100
804/804 [==============================] - 4s 5ms/step - loss: 0.8797 - accuracy: 0.6945
Epoch 19/100
804/804 [==============================] - 4s 5ms/step - loss: 0.8617 - accuracy: 0.6950
Epoch 20/100
804/804 [==============================] - 4s 5ms/step - loss: 0.8629 - accuracy: 0.6942
Epoch 21/100
804/804 [==============================] - 4s 5ms/step - loss: 0.8754 - accuracy: 0.6948
Epoch 22/100
804/804 [==============================] - 4s 5ms/step - loss: 0.8936 - accuracy: 0.6929
Epoch 23/100
804/804 [==============================] - 4s 5ms/step - loss: 0.8932 - accuracy: 0.6948
Epoch 24/100
804/804 [==============================] - 4s 5ms/step - loss: 0.9027 - accuracy: 0.6942
Epoch 25/100
804/804 [==============================] - 4s 5ms/step - loss: 0.9139 - accuracy: 0.6895
Epoch 26/100
804/804 [==============================] - 4s 5ms/step - loss: 0.9504 - accuracy: 0.6887
Epoch 27/100
804/804 [==============================] - 4s 5ms/step - loss: 0.9683 - accuracy: 0.6911
Epoch 28/100
804/804 [==============================] - 4s 5ms/step - loss: 0.9523 - accuracy: 0.6921
Epoch 29/100
804/804 [==============================] - 4s 5ms/step - loss: 0.8914 - accuracy: 0.6941
Epoch 30/100
804/804 [==============================] - 4s 5ms/step - loss: 0.8772 - accuracy: 0.6903
Epoch 31/100
804/804 [==============================] - 4s 5ms/step - loss: 0.8733 - accuracy: 0.6945
Epoch 32/100
804/804 [==============================] - 4s 5ms/step - loss: 0.8763 - accuracy: 0.6922
Epoch 33/100
804/804 [==============================] - 4s 5ms/step - loss: 0.8765 - accuracy: 0.6930
Epoch 34/100
804/804 [==============================] - 4s 5ms/step - loss: 0.8741 - accuracy: 0.6945
Epoch 35/100
804/804 [==============================] - 4s 5ms/step - loss: 0.9570 - accuracy: 0.6894
Epoch 36/100
804/804 [==============================] - 4s 5ms/step - loss: 0.9789 - accuracy: 0.6906
Epoch 37/100
804/804 [==============================] - 4s 5ms/step - loss: 0.9603 - accuracy: 0.6911
Epoch 38/100
804/804 [==============================] - 4s 5ms/step - loss: 0.9463 - accuracy: 0.6894
Epoch 39/100
804/804 [==============================] - 4s 5ms/step - loss: 0.9505 - accuracy: 0.6853
Epoch 40/100
804/804 [==============================] - 4s 5ms/step - loss: 0.9060 - accuracy: 0.6916
Epoch 41/100
804/804 [==============================] - 4s 5ms/step - loss: 0.8729 - accuracy: 0.6909
Epoch 42/100
804/804 [==============================] - 4s 5ms/step - loss: 0.9074 - accuracy: 0.6951
Epoch 43/100
804/804 [==============================] - 4s 5ms/step - loss: 0.9824 - accuracy: 0.6899
Epoch 44/100
804/804 [==============================] - 4s 5ms/step - loss: 0.9039 - accuracy: 0.6897
Epoch 45/100
804/804 [==============================] - 4s 5ms/step - loss: 0.9062 - accuracy: 0.6901
Epoch 46/100
804/804 [==============================] - 5s 6ms/step - loss: 0.9023 - accuracy: 0.6911
Epoch 47/100
804/804 [==============================] - 5s 6ms/step - loss: 0.8800 - accuracy: 0.6922
Epoch 48/100
804/804 [==============================] - 5s 6ms/step - loss: 0.8385 - accuracy: 0.6954
Epoch 49/100
804/804 [==============================] - 4s 5ms/step - loss: 0.8142 - accuracy: 0.6971
Epoch 50/100
804/804 [==============================] - 4s 5ms/step - loss: 0.8239 - accuracy: 0.6965
Epoch 51/100
804/804 [==============================] - 4s 5ms/step - loss: 0.9012 - accuracy: 0.6919
Epoch 52/100
804/804 [==============================] - 5s 6ms/step - loss: 0.9189 - accuracy: 0.6774
Epoch 53/100
804/804 [==============================] - 4s 6ms/step - loss: 0.8789 - accuracy: 0.6854
Epoch 54/100
804/804 [==============================] - 5s 6ms/step - loss: 0.8692 - accuracy: 0.6935
Epoch 55/100
804/804 [==============================] - 4s 5ms/step - loss: 0.7926 - accuracy: 0.6992
Epoch 56/100
804/804 [==============================] - 4s 5ms/step - loss: 0.7913 - accuracy: 0.6992
Epoch 57/100
804/804 [==============================] - 5s 6ms/step - loss: 0.7944 - accuracy: 0.6964
Epoch 58/100
804/804 [==============================] - 4s 5ms/step - loss: 0.8174 - accuracy: 0.6963
Epoch 59/100
804/804 [==============================] - 5s 6ms/step - loss: 0.8321 - accuracy: 0.6939
Epoch 60/100
804/804 [==============================] - 4s 6ms/step - loss: 0.8440 - accuracy: 0.6935
Epoch 61/100
804/804 [==============================] - 5s 6ms/step - loss: 0.8410 - accuracy: 0.6958
Epoch 62/100
804/804 [==============================] - 5s 6ms/step - loss: 0.8716 - accuracy: 0.6941
Epoch 63/100
804/804 [==============================] - 4s 5ms/step - loss: 0.8659 - accuracy: 0.6885
Epoch 64/100
804/804 [==============================] - 4s 6ms/step - loss: 0.8048 - accuracy: 0.6943
Epoch 65/100
804/804 [==============================] - 5s 6ms/step - loss: 0.7997 - accuracy: 0.6975
Epoch 66/100
804/804 [==============================] - 5s 6ms/step - loss: 0.7968 - accuracy: 0.6965
Epoch 67/100
804/804 [==============================] - 4s 6ms/step - loss: 0.7993 - accuracy: 0.6934
Epoch 68/100
804/804 [==============================] - 3s 4ms/step - loss: 0.8021 - accuracy: 0.6963
Epoch 69/100
804/804 [==============================] - 5s 6ms/step - loss: 0.8008 - accuracy: 0.6957
Epoch 70/100
804/804 [==============================] - 4s 6ms/step - loss: 0.8012 - accuracy: 0.6941
Epoch 71/100
804/804 [==============================] - 5s 6ms/step - loss: 0.7836 - accuracy: 0.6962
Epoch 72/100
804/804 [==============================] - 5s 6ms/step - loss: 0.7787 - accuracy: 0.6980
Epoch 73/100
804/804 [==============================] - 5s 6ms/step - loss: 0.8066 - accuracy: 0.6971
Epoch 74/100
804/804 [==============================] - 4s 6ms/step - loss: 0.8019 - accuracy: 0.6923
Epoch 75/100
804/804 [==============================] - 4s 5ms/step - loss: 0.7688 - accuracy: 0.6981
Epoch 76/100
804/804 [==============================] - 5s 6ms/step - loss: 0.7557 - accuracy: 0.6974
Epoch 77/100
804/804 [==============================] - 5s 6ms/step - loss: 0.7227 - accuracy: 0.6998
Epoch 78/100
804/804 [==============================] - 5s 6ms/step - loss: 0.7710 - accuracy: 0.6988
Epoch 79/100
804/804 [==============================] - 5s 6ms/step - loss: 0.7239 - accuracy: 0.6988
Epoch 80/100
804/804 [==============================] - 5s 6ms/step - loss: 0.7461 - accuracy: 0.7000
Epoch 81/100
804/804 [==============================] - 4s 5ms/step - loss: 0.7490 - accuracy: 0.6995
Epoch 82/100
804/804 [==============================] - 5s 6ms/step - loss: 0.7363 - accuracy: 0.7037
Epoch 83/100
804/804 [==============================] - 4s 5ms/step - loss: 0.7504 - accuracy: 0.6962
Epoch 84/100
804/804 [==============================] - 4s 5ms/step - loss: 0.7330 - accuracy: 0.7015
Epoch 85/100
804/804 [==============================] - 4s 5ms/step - loss: 0.7213 - accuracy: 0.7010
Epoch 86/100
804/804 [==============================] - 5s 6ms/step - loss: 0.7485 - accuracy: 0.6995
Epoch 87/100
804/804 [==============================] - 4s 5ms/step - loss: 0.7391 - accuracy: 0.7010
Epoch 88/100
804/804 [==============================] - 4s 5ms/step - loss: 0.7236 - accuracy: 0.7028
Epoch 89/100
804/804 [==============================] - 4s 5ms/step - loss: 0.7204 - accuracy: 0.7021
Epoch 90/100
804/804 [==============================] - 4s 5ms/step - loss: 0.7204 - accuracy: 0.7035
Epoch 91/100
804/804 [==============================] - 4s 5ms/step - loss: 0.7132 - accuracy: 0.7022
Epoch 92/100
804/804 [==============================] - 4s 5ms/step - loss: 0.7074 - accuracy: 0.7013
Epoch 93/100
804/804 [==============================] - 4s 5ms/step - loss: 0.7221 - accuracy: 0.7018
Epoch 94/100
804/804 [==============================] - 4s 5ms/step - loss: 0.7182 - accuracy: 0.7043
Epoch 95/100
804/804 [==============================] - 4s 5ms/step - loss: 0.7182 - accuracy: 0.7014
Epoch 96/100
804/804 [==============================] - 4s 5ms/step - loss: 0.7165 - accuracy: 0.7035
Epoch 97/100
804/804 [==============================] - 5s 6ms/step - loss: 0.7195 - accuracy: 0.7044
Epoch 98/100
804/804 [==============================] - 4s 5ms/step - loss: 0.7078 - accuracy: 0.7035
Epoch 99/100
804/804 [==============================] - 4s 5ms/step - loss: 0.7059 - accuracy: 0.7029
Epoch 100/100
804/804 [==============================] - 4s 5ms/step - loss: 0.7089 - accuracy: 0.7039

#### Alternative Model 2

In [40]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

91

In [42]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [43]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = (number_input_features + 1) // 2

# Define the number of hidden nodes for the second hidden layer
# Adding a 2nd layer to improve the nn
hidden_nodes_layer2 = (hidden_nodes_layer1_A2 + 1) // 2

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

46

In [44]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [45]:
# First hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Add the second hidden
nn_A2.add(Dense(units=hidden_nodes_layer2, activation="relu"))

# Output layer
nn_A2.add(Dense(units=1, activation="linear"))

# Check the structure of the model
nn_A2.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_5 (Dense)             (None, 46)                4232

 dense_6 (Dense)             (None, 23)                1081

 dense_7 (Dense)             (None, 1)                 24

=================================================================
Total params: 5337 (20.85 KB)
Trainable params: 5337 (20.85 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [46]:
# Compile the model
nn_A2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [47]:
# Fit the model
fit_model_A2 = nn_A2.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 7s 6ms/step - loss: 0.9539 - accuracy: 0.6728
Epoch 2/50
804/804 [==============================] - 5s 6ms/step - loss: 0.8800 - accuracy: 0.6922
Epoch 3/50
804/804 [==============================] - 5s 6ms/step - loss: 0.8774 - accuracy: 0.6893
Epoch 4/50
804/804 [==============================] - 4s 5ms/step - loss: 0.8048 - accuracy: 0.6953
Epoch 5/50
804/804 [==============================] - 4s 5ms/step - loss: 1.2012 - accuracy: 0.6725
Epoch 6/50
804/804 [==============================] - 4s 6ms/step - loss: 1.3008 - accuracy: 0.6727
Epoch 7/50
804/804 [==============================] - 4s 6ms/step - loss: 1.1901 - accuracy: 0.6756
Epoch 8/50
804/804 [==============================] - 4s 5ms/step - loss: 1.2905 - accuracy: 0.6734
Epoch 9/50
804/804 [==============================] - 4s 5ms/step - loss: 1.2922 - accuracy: 0.6714
Epoch 10/50
804/804 [==============================] - 4s 5ms/step - loss: 1.2891 - accuracy: 0.6729
Epoch 11/50
804/804 [==============================] - 4s 5ms/step - loss: 1.2864 - accuracy: 0.6741
Epoch 12/50
804/804 [==============================] - 5s 6ms/step - loss: 1.2586 - accuracy: 0.6761
Epoch 13/50
804/804 [==============================] - 4s 5ms/step - loss: 1.2579 - accuracy: 0.6753
Epoch 14/50
804/804 [==============================] - 4s 6ms/step - loss: 1.2569 - accuracy: 0.6754
Epoch 15/50
804/804 [==============================] - 4s 5ms/step - loss: 0.9516 - accuracy: 0.6907
Epoch 16/50
804/804 [==============================] - 4s 5ms/step - loss: 0.8400 - accuracy: 0.6986
Epoch 17/50
804/804 [==============================] - 4s 6ms/step - loss: 0.8075 - accuracy: 0.6993
Epoch 18/50
804/804 [==============================] - 4s 5ms/step - loss: 0.8039 - accuracy: 0.6982
Epoch 19/50
804/804 [==============================] - 5s 6ms/step - loss: 0.8014 - accuracy: 0.6972
Epoch 20/50
804/804 [==============================] - 5s 6ms/step - loss: 0.8623 - accuracy: 0.6954
Epoch 21/50
804/804 [==============================] - 5s 6ms/step - loss: 0.8854 - accuracy: 0.6919
Epoch 22/50
804/804 [==============================] - 5s 6ms/step - loss: 0.8013 - accuracy: 0.6964
Epoch 23/50
804/804 [==============================] - 5s 6ms/step - loss: 0.7413 - accuracy: 0.6984
Epoch 24/50
804/804 [==============================] - 4s 5ms/step - loss: 0.7518 - accuracy: 0.7021
Epoch 25/50
804/804 [==============================] - 4s 5ms/step - loss: 0.7630 - accuracy: 0.7002
Epoch 26/50
804/804 [==============================] - 4s 6ms/step - loss: 0.7629 - accuracy: 0.7009
Epoch 27/50
804/804 [==============================] - 4s 5ms/step - loss: 0.7563 - accuracy: 0.6982
Epoch 28/50
804/804 [==============================] - 4s 5ms/step - loss: 0.7452 - accuracy: 0.7017
Epoch 29/50
804/804 [==============================] - 4s 5ms/step - loss: 0.7613 - accuracy: 0.7002
Epoch 30/50
804/804 [==============================] - 4s 5ms/step - loss: 0.7432 - accuracy: 0.7010
Epoch 31/50
804/804 [==============================] - 5s 6ms/step - loss: 0.7604 - accuracy: 0.7015
Epoch 32/50
804/804 [==============================] - 4s 5ms/step - loss: 0.7689 - accuracy: 0.6995
Epoch 33/50
804/804 [==============================] - 4s 5ms/step - loss: 0.7675 - accuracy: 0.6988
Epoch 34/50
804/804 [==============================] - 4s 5ms/step - loss: 0.7654 - accuracy: 0.7024
Epoch 35/50
804/804 [==============================] - 5s 6ms/step - loss: 0.7965 - accuracy: 0.6985
Epoch 36/50
804/804 [==============================] - 4s 5ms/step - loss: 0.7755 - accuracy: 0.7014
Epoch 37/50
804/804 [==============================] - 4s 6ms/step - loss: 0.7588 - accuracy: 0.6980
Epoch 38/50
804/804 [==============================] - 4s 5ms/step - loss: 0.7123 - accuracy: 0.7038
Epoch 39/50
804/804 [==============================] - 5s 6ms/step - loss: 0.7264 - accuracy: 0.7020
Epoch 40/50
804/804 [==============================] - 4s 5ms/step - loss: 0.7488 - accuracy: 0.6946
Epoch 41/50
804/804 [==============================] - 5s 6ms/step - loss: 0.7349 - accuracy: 0.7015
Epoch 42/50
804/804 [==============================] - 4s 5ms/step - loss: 0.7306 - accuracy: 0.7020
Epoch 43/50
804/804 [==============================] - 4s 5ms/step - loss: 0.7364 - accuracy: 0.7011
Epoch 44/50
804/804 [==============================] - 4s 5ms/step - loss: 0.7062 - accuracy: 0.7004
Epoch 45/50
804/804 [==============================] - 4s 5ms/step - loss: 0.7005 - accuracy: 0.7038
Epoch 46/50
804/804 [==============================] - 4s 5ms/step - loss: 0.7130 - accuracy: 0.7032
Epoch 47/50
804/804 [==============================] - 4s 5ms/step - loss: 0.7156 - accuracy: 0.7030
Epoch 48/50
804/804 [==============================] - 4s 5ms/step - loss: 0.7116 - accuracy: 0.7037
Epoch 49/50
804/804 [==============================] - 4s 5ms/step - loss: 0.7136 - accuracy: 0.7018
Epoch 50/50
804/804 [==============================] - 4s 5ms/step - loss: 0.7018 - accuracy: 0.7025

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [48]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
268/268 - 0s - loss: 0.5810 - accuracy: 0.7082 - 468ms/epoch - 2ms/step
Loss: 0.5809672474861145, Accuracy: 0.7082215547561646

In [49]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled,y_test,verbose=2)
# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
268/268 - 1s - loss: 0.7221 - accuracy: 0.7054 - 1s/epoch - 5ms/step
Loss: 0.7220852971076965, Accuracy: 0.7054227590560913

In [50]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled,y_test,verbose=2)
# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
268/268 - 1s - loss: 0.6880 - accuracy: 0.7055 - 1s/epoch - 5ms/step
Loss: 0.6880361437797546, Accuracy: 0.705539345741272

### Step 3: Save each of your alternative models as an HDF5 file.

In [52]:
# Set the file path for the first alternative model
file_path = Path("Resources/AlphabetSoup_nn2.h5")

# Export your model to an HDF5 file
nn_A1.save(file_path)

In [53]:
# Set the file path for the second alternative model
file_path = Path("Resources/AlphabetSoup_nn3.h5")

# Export your model to an HDF5 file
nn_A2.save(file_path)